### ISSUE TITLE
DatabaseSecretEngineConfig's password rotation messes up vault's password rotation

### ISSUE THREAD

**Issue by ameyp** [redhat-cop/vault-config-operator#105]
I have the following DatabaseSecretEngineConfig:

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineConfig
metadata:
  name: test-db
spec:
  allowedRoles:
    - '*'
  authentication:
    path: kubernetes
    role: vault-config-operator
    serviceAccount:
      name: default
  connectionURL: >-
    postgresql://{{username}}:{{password}}@pg.example.com/test-db
  path: database/test-db
  pluginName: postgresql-database-plugin
  rootCredentials:
    usernameKey: username
    passwordKey: password
    secret:
      name: password-secret
  rootPasswordRotation:
    enable: true
    rotationPeriod: 168h
  verifyConnection: true
```

and the following DatabaseSecretEngineStaticRole:

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineStaticRole
metadata:
  name: test-role
spec:
  authentication:
    path: kubernetes
    role: vault-config-operator
    serviceAccount:
      name: default
  credentialType: password
  dBName: test-db
  passwordCredentialConfig: {}
  path: database/test-db
  rotationPeriod: 86400
  rotationStatements:
    - ALTER USER "{{name}}" WITH PASSWORD '{{password}}';
  username: test-user
```

Once a day, vault starts logging errors because it cannot login to the database to rotate the static role's password:

```
2023-01-06T18:26:25.200Z [ERROR] secrets.database.database_xxxxxx: unable to rotate credentials in periodic function: error="error verifying connection: failed to connect to `host=pg.example.com user=test-user database=my-db`: failed SASL auth (FATAL: password authentication failed for user \"test-user\" (SQLSTATE 28P01))"
```

I did not have this issue before I started using the operator to manage resources, so it's likely that it's somehow caused by the operator. FWIW I'm only seeing this for PostgreSQL databases, not for MySQL ones.
