### ISSUE TITLE
Common connection | skipVerify not properly set

### ISSUE THREAD

**Issue by erlisb** [redhat-cop/vault-config-operator#121]
There is a minor issue with the common connection section, with **tLSConfig.skipVerify**.
If you set the config as follows : 

```
  connection:
    address: 'https://vault-a.xxxx.xxxx'
    tLSConfig:
      skipVerify: True
```

this is translated into : 

`tlsConfig.Insecure = !vc.TLSConfig.SkipVerify  --> tlsConfig.Insecure = False`

which is then skipped in the vault client api : 

```
if t.Insecure {
   clientTLSConfig.InsecureSkipVerify = true
}
```

Am I missing something, or is this intended ?

Thnx.
