### ISSUE TITLE
VaultSecret refreshPeriod : default behavior with default configurations

### ISSUE THREAD

**Issue by MrLuje** [redhat-cop/vault-config-operator#129]
This is a question as I'm not sure what should happen with the default behavior of vault + operator.

I have created a bunch of `VaultSecret` like the following :
```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: keycloak-secret
spec:
  vaultSecretDefinitions:
    - authentication:
        path: k8s/kubernetes
        role: tooling_dev-secret-reader
      name: keycloak_secret
      path: k8s/tooling_dev/namespace/tooling_dev/kv-namespace/data/keycloak-secret
  output:
    name: oauth2
    type: Opaque
    stringData:
      SOME: thing
```
and when looking at the operator logs, I'm seeing a lot of `DEBUG    controllers.VaultSecret    Sync VaultSecret    {"namespacedName": "tooling-dev/keycloak-secret}`, like 1 every 1s for each `VaultSecret`.
If I specify `VaultSecret.refreshPeriod` to `1m`, the logs lower to 1 every 1m as expected.

The `VaultSecret.refreshPeriod` doc states `This takes precedence over any vault secret lease duration and can be used to force a refresh.` 
https://github.com/redhat-cop/vault-config-operator/blob/c56bae042a91187169f84b63373ba5dd075afdff/config/crd/bases/redhatcop.redhat.io_vaultsecrets.yaml#L69-L72
By default, `auth` & `mount` have `default_lease_ttl` & `max_lease_ttl` to 0. 
Is it evaluated as "since I have no idea when it will expires, I'll request it more often" ?

**Comment by MrLuje** [comment]
I added 1h of `default_lease_ttl` & `max_lease_ttl` to the mount and it doesn't have any effect on the refresh rate

**Comment by trevorbox** [comment]
Does the behavior work as documented if the SecretEngineMount is v2? This might just mean there is no lease information for v1 kv secrets. Regardless, it would be good to document that better.
Example:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: kv-v2
spec:
  authentication: 
    path: kubernetes
    role: kv-engine-admin-v2
  type: kv
  path: test-vault-config-operator
  options:
    version: "2"
```
