### ISSUE TITLE
Database secret engine root credentials rotation is overwritten by resource reconciliation and credentials are lost

### ISSUE THREAD

**Issue by davoustp** [redhat-cop/vault-config-operator#131]
Hi,
It looks like the root credential rotation is failing - not because it fails to invoke the Vault `root-rotation` endpoint (this works fine), but because it updates the connection right after the rotation _including the original-but-now-outdated root credentials_.

As a result the root credentials are lost, and Vault cannot connect to the database engine any more, leading to failure for any database-related operation: dynamic or static secrets creation / revocation, another root credential rotation...

### Environment
* Kubernetes cluster 1.24.8 (GKE)
* vault 1.12.1 (deployed using helm)
* vault-config-operator version 0.8.10 (deployed using Helm)

### Configuration

Initial root credentials are set into a Kubernetes secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-vault-initialpassword
  namespace: postgres-test
type: Opaque
data:
  password: "<REDACTED>"
```

Note: this also happens with `RandomSecret` as well (but is more noisy to troubleshoot because more requests are sent to vault)

The database secret engine config is as below:
```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineConfig
metadata:
  name: postgres-alpha
  namespace: postgres-test
spec:
  authentication:
    path: kubernetes
    role: database-admin
    serviceAccount:
      name: sa-vault-database-admin
  pluginName: postgresql-database-plugin
  allowedRoles:
    - "*"
  connectionURL: postgresql://{{username}}:{{password}}@postgres-alpha-headless.postgres-test.svc:5432/postgres
  path: database/postgres-test/postgres-alpha
  username: vault
  rootCredentials:
    passwordKey: password
    secret:
      name: postgres-vault-initialpassword
  rootPasswordRotation:
    enable: true
    rotationPeriod: 10m
  passwordPolicy: alphanum-with-special-chars
  databaseSpecificConfig:
    username_template: '{{.RoleName | truncate 47}}-{{random 4}}-{{unix_time}}'
```

When attempting to drive vault to interact with the database, database authentication errors show up:
```
URL: PUT https://vault-active.vault:8200/v1/database/postgres-test/postgres-alpha/rotate-root/postgres-alpha                                                                                                                                             
Code: 500. Errors:                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                         
* 1 error occurred:                                                                                                                                                                                                                                      
    * error verifying connection: failed to connect to `host=postgres-alpha-headless.postgres-test.svc user=vault database=postgres`: failed SASL auth (FATAL: password authentication failed for user "vault" (SQLSTATE 28P01))                         
```

### Analysis

This requires enabling vault audit capability:
```
kubectl exec -it -n vault vault-0 -- sh -c 'vault audit enable file file_path=stdout'
```

Audit log generated by the sequence above is attached to this issue for completeness:
[vault-database-root-rotation-failure.log](https://github.com/redhat-cop/vault-config-operator/files/10873746/vault-database-root-rotation-failure.log)

#### Scenario:
* before audit logging is enabled
  * the `DatabaseSecretEngineConfig` object is set without root rotation enabled
  * database dynamic credential generation is checked and works OK
* then:
  * the `DatabaseSecretEngineConfig` object is modified to enable root rotation
  * database dynamic credential generation is attempted and fails

#### Observed interactions with vault

The sequence which can be seen from the audit log goes as below:
1. kubernetes authentication to acquire a vault token
2. read the existing database secret engine config from vault
3. database secret engine config is updated into vault
4. database engine root credentials rotation is performed
5. (yet another kubernetes authentication happens here)
6. read the existing database secret engine config from vault
7. database secret engine config is updated into vault again
8. dynamic credentials is requested and fail with database authentication failure

It looks like the `DatabaseSecretEngineConfig` CR object is updated in Kubernetes after the root rotation (status update, probably), which triggers yet another reconciliation.

Problem here is that step 6 does NOT retrieve the rotated password (that's the all point).
But the reconciliation logic DOES set the `password` attribute in the config update request:
```json
{
  "time": "2023-03-02T16:16:32.398233309Z",
  "type": "request",
  "auth": {
     ...
  },
  "request": {
    ...
    "data": {
      "allowed_roles": [
        "hmac-sha256:f25198ddce0c77d0eda570ea020978e3a18df0501bd489bdc1aceca5c444cd4c"
      ],
      "connection_url": "hmac-sha256:d6b9d82a62842b12071400c04f68f63dd34b9c25e5e5cbbce646c8a48fdfaa5b",
      "disable_escaping": false,
      "password": "hmac-sha256:2dc1b3be5d50abac97a24cd80e36f03851a21d214bc30d925a698bd9b15bbed4",
      "password_policy": "hmac-sha256:472c8a83a618bdd6ab035c5d6a4448a2604e15fa4f9af8db96d0c7ce6e998ff0",
      "plugin_name": "hmac-sha256:4c61ac7aac21902d25e0745cd36c81201e1e2305dc79b0a4ae7b029d90237bdd",
      "plugin_version": "hmac-sha256:7a648518ff4e63b78309be7cbc2e599e1a523363dd9ee4d1617a39f70d318808",
      "root_credentials_rotate_statements": [],
      "username": "hmac-sha256:026ea08099d4c8771183494ea38015248974c226ac1bf1e5ca9bf286bc81e115",
      "username_template": "hmac-sha256:375858b438ca5069cd20bb8a55753e2d378f2ed4adea219970bf8f41a0c0c39d",
      "verify_connection": false
    },
    "remote_address": "10.40.2.25",
    "remote_port": 58672
  }
}
```

As far as I understand, this config update request will *overwrite* the root credentials that was just generated in Vault's config, which is now out-of-sync with the database credentials.

**Comment by davoustp** [comment]
I confirm that this is the root cause of the root credentials loss, see below.

### How to reproduce in a simple manner

Using the same mounts and configuration as above:

1. Setup the `DatabaseSecretEngineConfig` custom resource
2. Verify that credentials can be generated successfully:
  `kubectl exec -it -n vault vault-0 -- sh -c 'vault read database/postgres-test/postgres-alpha/creds/test'`
3. Rotate the root credentials using either vault UI or CLI:
  `kubectl exec -it -n vault vault-0 -- sh -c 'database/postgres-test/postgres-alpha/rotate-root/postgres-alpha'`
4. Verify that credentials are still generated successfully
5. Update the `DatabaseSecretEngineConfig` custom resource (-> operator pushes the change to vault)
6. Attempt to generate credentials generates the database authentication error

### Confirming the root cause

Instead of using the operator to update the database secret engine's configuration at step 5, use the following job below:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: rotate-root-and-update-config
  namespace: postgres-test
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'database-admin'
        vault.hashicorp.com/agent-inject-token: 'true'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-cache-enable: 'false'
        vault.hashicorp.com/ca-cert: '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
    spec:
      serviceAccountName: sa-vault-database-admin
      containers:
      - name: console
        image: alpine:3.17
        env:
          - name: VAULT_ADDR
            value: "https://vault-active.vault:8200"
        command:
        - /bin/sh
        - -c
        - |
          set -euo pipefail
          apk --no-cache add curl jq
          VAULT_TOKEN=$(cat /vault/secrets/token)

          curl -vvv --fail -L -X POST -H "X-Vault-Token: $VAULT_TOKEN" \
            --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
            ${VAULT_ADDR}/v1/database/postgres-test/postgres-alpha/config/postgres-alpha \
            -H "Content-Type: application/json" \
            -d '{"username_template": "{{.RoleName | truncate 39}}-{{random 4}}-{{unix_time}}"}'

      restartPolicy: Never
  backoffLimit: 4
```

=> the payload of this Vault API request is a partial update: the JSON only contains what has changed, and *does not contain the `password`attribute*.

This is what the Vault UI is doing.

You can then confirm that the update was properly taken into account by checking the database connection details using Vault CLI (`truncate` is set to `39` chars instead of the original `47`).

Then generate credentials again as step 6: this is successfully performed.
