### ISSUE TITLE
DatabaseSecretEngineConfig root password is not being rotated

### ISSUE THREAD

**Issue by ameyp** [redhat-cop/vault-config-operator#136]
Steps to reproduce:
- Create a kubernetes secret with the initial password
- Login to database (postgresql in my case) and create a role with the same password
- Create a `DatabaseSecretEngineConfig` with the following content:

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineConfig
metadata:
  name: tandoor
  namespace: vault
spec:
  allowedRoles:
    - '*'
  authentication:
    path: kubernetes
    role: operator
    serviceAccount:
      name: default
  connectionURL: >-
    postgresql://{{username}}:{{password}}@postgres.example.com/tandoor?sslmode=require
  path: databases/postgresql
  pluginName: postgresql-database-plugin
  rootCredentials:
    passwordKey: password
    secret:
      name: tandoor-initial-creds
    usernameKey: username
  rootPasswordRotation:
    enable: true
    rotationPeriod: 168h
  verifyConnection: true

```

In the operator logs, I see:

```
2023-04-08T16:59:51.648Z	DEBUG	root credentials rotation already occurred - credentials retrieval skipped	{"controller": "databasesecretengineconfig", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "DatabaseSecretEngineConfig", "DatabaseSecretEngineConfig": {"name":"tandoor","namespace":"vault"}, "namespace": "vault", "name": "tandoor", "reconcileID": "a258fb1c-eca3-4e32-a60c-6865360a4a04"}
```

However, no `rotate-root` is received by vault according to its audit log, and I can still manually login to the database with that role and the same initial password.
