### ISSUE TITLE
vault-config-operator resource seems to stay out-of-sync

### ISSUE THREAD

**Issue by davoustp** [redhat-cop/vault-config-operator#162]
## Symptom

A vault-config-operator custom resource seems to stay out-of-sync for days without vault-config-operator attempting to reconcile the CR with the Vault underlying resource.

Resource partial description from k8s (full redacted description available if required):
```yaml
Spec:
  Authentication:
    Path:  kubernetes
    Role:  <REDACTED>
    Service Account:
      Name:             <REDACTED>
  isKVSecretsEngineV2:  true
  Path:                 <REDACTED>
  Secret Format:
    Password Policy Name:  alphanum-with-special-chars
  Secret Key:              secret
Status:
  Conditions:
    Last Transition Time:    2023-06-12T03:46:30Z
    Message:                 Put "https://vault-active.vault:8200/v1/auth/kubernetes/login": dial tcp 10.0.16.94:8200: connect: connection refused
    Observed Generation:     1
    Reason:                  LastReconcileCycleFailed
    Status:                  False
    Type:                    ReconcileSuccessful
  Last Vault Secret Update:  2023-06-08T04:02:44Z
Events:                      <none>
```

No event is recorded, and the CR stays with `Status.Conditions.Status` set to `false`.

Versions:
* vault:1.13.0
* vault-config-operator:v0.8.15

Special conditions:
Cluster is shut down at night and during weekends - but the vault-config-operator shows that it stayed up (investigation underway to understand why).
Custom Resources are created and updated in k8s using argocd.

## Investigations

Running on a local k8s cluster: when vault is down (k8s is still up) and that vault-conf-operator is running and has to reconcile a CR (because updated), then it errors out, but:
* it updates the CR state flag (used in the condition) and keep on trying until it is successful
* it adds an event to the CR for human understanding of what's happening

Attempting to find out a reproducible case.
