### ISSUE TITLE
kv-v2 secret is erroneously updated upon operator restart

### ISSUE THREAD

**Issue by davoustp** [redhat-cop/vault-config-operator#163]
### Context

* Kubernetes: v1.25.0
* Vault: 1.13.1
* vault-config-operator: v0.8.15

### Symptom

Creating a fresh `RandomSecret` with kv-v2 enabled but without any refresh creates the corresponding secret in Vault with version 1.

Example of such `RandomSecret`:
```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: randomsecret
  namespace: test
spec:
  authentication: 
    path: kubernetes
    role: kv-creator
    serviceAccount:
      name: sa-vault-kv-creator
  isKVSecretsEngineV2: true
  path: kv/data/test
  secretKey: password
  secretFormat:
    passwordPolicyName: alphanum-without-special-chars
```
 
But restarting the operator generates another random value and updates the secret to version 2, while it's not supposed to.

Impact is high, as an operator restart can happen any time, out of control from a deployment perspective, breaking the contract and leaving apps with a wrong secret value.

### Analysis

The `RandomSecret` controller relies onto the presence of field `status.lastVaultSecretUpdate` in the k8s resource to detect that a random value has already been generated. If this field is not present, or if refresh is configured and it's time to update it, then it continues the reconciliation logic, creating the appropriate random value and propagates these changes to Vault.
So far so good.

Then it sets the field `status.lastVaultSecretUpdate` with the current timestamp, and performs the k8s resource update with appropriate details, such as adding the finalizer if not present, adding/updating the `status.conditions` and all modifications performed to the object in memory, using https://github.com/redhat-cop/vault-config-operator/blob/47c99b4ebd0e0995ea39f44c92dd72bb663ccb55/controllers/vaultresourcecontroller/utils.go#L35

Or so it seems...

Problem lies at https://github.com/redhat-cop/vault-config-operator/blob/47c99b4ebd0e0995ea39f44c92dd72bb663ccb55/controllers/vaultresourcecontroller/utils.go#L40-L47 :

As noted in https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.13.0/pkg/client#Writer.Update:
> // Update updates the given obj in the Kubernetes cluster. obj must be a
	// struct pointer so that obj can be updated with the content returned by the Server.
	Update(ctx [context](https://pkg.go.dev/context).[Context](https://pkg.go.dev/context#Context), obj [Object]

This means that the `Update` operation *mutates* the passed-in object with the response from k8s.
And since k8s does not know anything about changes that are yet to occur, these changes are lost...
and so is the `status.lastVaultSecretUpdate`.

As a result, the k8s resource only contains the `status.conditions` field, but no `status.lastVaultSecretUpdate`.

When the operator restarts, it will then scan the `RandomResource` again, but then will trigger the secret generation because the field is not found.
This time, the reconciliation code will actually set the `status.lastVaultSecretUpdate` field correctly, because the finalizer is already present, and the mutating `Update` call does not take place...
