### ISSUE TITLE
JWT authentication engine mount can not be created if OIDCCredentials.secret is not set

### ISSUE THREAD

**Issue by snakebyte91** [redhat-cop/vault-config-operator#165]
If `OIDCCredentials.secret.name` is not specified the JWT authentication engine mount can not be configured. I get an error message like "no meanings found for secret".

```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineConfig
metadata:
  name: gitlab
spec:
  authentication:
    path: kubernetes
    role: my-policy
    serviceAccount:
      name: my-sa
  connection:
    address: 'https://vault.example.com:8200'
  boundIssuer: gitlab.example.com
  JWKSURL: https://gitlab.example.com/-/jwks
  path: vault-config-operator/jwt
```

**Comment by erlisb** [comment]
@snakebyte91 I guess you get the following error: 

```
 {"controller": "jwtoidcauthengineconfig", "controllerGroup": "redhatcop.redhat.io", 
 "controllerKind": "JWTOIDCAuthEngineConfig", "JWTOIDCAuthEngineConfig": {"name":"gitlab","namespace":"vault-admin"}, 
 "namespace": "vault-admin", "name": "gitlab", "reconcileID": "651f4a79-3273-4e60-9325-b7b1da0156b6", 
 "error": "no means of retrieving a secret was specified"}
```

I applied a small [fix#165](https://github.com/redhat-cop/vault-config-operator/pull/167)

@raffaelespazzoli, what do you think ?

**Comment by snakebyte91** [comment]
@snakebyte91 Yes, I got this error.

**Comment by erlisb** [comment]
@snakebyte91 this should be fixed with the current release.
Can you check it and close this issue ?

**Comment by snakebyte91** [comment]
@erlisb I still get the error `no means of retrieving a secret was specified`

Vault config operator version: v0.8.17

```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineConfig
metadata:
  name: gitlab
spec:
  authentication:
    path: kubernetes
    role: policy-vault-config-operator
    serviceAccount:
      name: controller-manager
  connection:
    address: 'https://vault.example.com:8200'
  boundIssuer: https://git.example.com.de
  JWKSURL: https://git.example.com/-/jwks
  path: jwt
```

**Comment by erlisb** [comment]
@snakebyte91 are you sure you are using the latest VCO release or if you upgraded to the lastest CRD versions ? 

I just tried your config and I get a different error :

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: AuthEngineMount
metadata:
  name: gitlab-jwt
spec:
  authentication: 
    path: kubernetes
    role: vault-admin
  type: oidc
  path: jwt
```

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineConfig
metadata:
  name: gitlab
spec:
  authentication:
    path: kubernetes
    role: vault-admin
    serviceAccount:
      name: default
  boundIssuer: https://git.example.com.de
  JWKSURL: https://git.example.com/-/jwks
  path: jwt/gitlab-jwt
```

error: 

`1.6910676757404606e+09  ERROR   unable to create/update vault resource  {"controller": "jwtoidcauthengineconfig", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "JWTOIDCAuthEngineConfig", "JWTOIDCAuthEngineConfig": {"name":"gitlab","namespace":"vault-admin"}, "namespace": "vault-admin", "name": "gitlab", "reconcileID": "43c5ec1b-51c6-4490-aa60-de0fb6eb2e91", "instance": {"apiVersion": "redhatcop.redhat.io/v1alpha1", "kind": "JWTOIDCAuthEngineConfig", "namespace": "vault-admin", "name": "gitlab"}, "error": "Error making API request.\n\nURL: PUT https://vault.vault.svc.cluster.local:8200/v1/auth/jwt/gitlab-jwt/config\nCode: 400. Errors:\n\n* error checking jwks URL"}`

which is expected, since JWKSURL is a non-existing one.

Can you recheck ?
