### ISSUE TITLE
OIDC auth engine config: both 'oidc_client_id' and 'oidc_client_secret' must be set for OIDC

### ISSUE THREAD

**Issue by snakebyte91** [redhat-cop/vault-config-operator#166]
I get the following error when I try to configure OIDC:

Error message: `Error making API request. URL: PUT https://vault.example.com:8200/v1/auth/vault-config-operator/oidc/config Code: 400. Errors: * both 'oidc_client_id' and 'oidc_client_secret' must be set for OIDC`

**JWTOIDCAuthEngineConfig**
```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineConfig
metadata:
  name: oidc
spec:
  authentication:
    path: kubernetes
    role: policy-vault-config-operator
    serviceAccount:
      name: controller-manager
  connection:
    address: 'https://vault.example.com:8200'
  OIDCCredentials:
    secret:
      name: oidc
    usernameKey: oidc_client_id
    passwordKey: oidc_client_secret
  OIDCDiscoveryURL: "https://login.microsoftonline.com/<id>/v2.0"
  path: vault-config-operator/oidc
  providerConfig:
    {
      "provider": "azure"
    }
```

**Secret**

```yaml
apiVersion: v1
data:
  oidc_client_id: <client_id_removed>
  oidc_client_secret: <client_secret_removed>
immutable: false
kind: Secret
metadata:
  annotations:
  name: oidc
  namespace: vault-config-operator
  ownerReferences:
  - apiVersion: external-secrets.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: oidc
    uid: ebe5a701-8d5c-4487-9273-5a13688f4a6f
  resourceVersion: "166887981"
  uid: c8ca1186-1ada-488e-ac9d-c64297639eea
type: Opaque
```

**Comment by erlisb** [comment]
Can you set the OIDCClientID, in your JWTOIDCAuthEngineConfig CR ? 
The logic for retrieving OIDCCredentials is a follows : 

`if r.Spec.OIDCClientID == "" {
r.SetUsernameAndPassword(string(secret.Data[r.Spec.OIDCCredentials.UsernameKey]), string(secret.Data[r.Spec.OIDCCredentials.PasswordKey]))
} else {
r.SetUsernameAndPassword(r.Spec.JWTOIDCConfig.OIDCClientID, string(secret.Data[r.Spec.OIDCCredentials.PasswordKey]))

}`

Thnx.

**Comment by snakebyte91** [comment]
When I set `OIDCClientID` it is working.

**Comment by erlisb** [comment]
@snakebyte91  If you don't o set `OIDCClientID `, you can also set `Spec.OIDCCredentials.UsernameKey` directly.
If everything works as expected, can you close this issue ?

**Comment by snakebyte91** [comment]
@erlisb What do you mean with 'directly'?

This snippet is not working:

```yaml
spec:
  OIDCCredentials:
    secret:
      name: oidc
    usernameKey: oidc_client_id
    passwordKey: oidc_client_secret
```

**Comment by erlisb** [comment]
@snakebyte91, I meant the following : 

```
spec:
  OIDCClientID: ""
  OIDCCredentials:
    secret:
      name: oidc
    usernameKey: oidc_client_id
    passwordKey: oidc_client_secret
```

this should work, as shown below : 

```
if r.Spec.OIDCClientID == "" {
r.SetUsernameAndPassword(string(secret.Data[r.Spec.OIDCCredentials.UsernameKey]), string(secret.Data[r.Spec.OIDCCredentials.PasswordKey]))
} else {
r.SetUsernameAndPassword(r.Spec.JWTOIDCConfig.OIDCClientID, string(secret.Data[r.Spec.OIDCCredentials.PasswordKey]))
}
```

**Comment by snakebyte91** [comment]
When I try this I get the same error message:

```
Error making API request.

URL: PUT
https://vault.example.com:8200/v1/auth/oidc/config

Code: 400. Errors:
* both 'oidc_client_id' and 'oidc_client_secret' must be set for OIDC
```

**Comment by erlisb** [comment]
Can you check if the secret is properly set with the correct UsernameKey and PasswordKey and see if they are correctly referenced in your CR ?

Thnx.

**Comment by snakebyte91** [comment]
K8s secret created as shown in the example:

```bash
kubectl create secret generic oidccredentials --from-literal=oidc_client_id="123456-1234-1234-1234-123456789" --from-literal=oidc_client_secret="saffsfsdfsfsdgsdgsdgsdgghdfhdhdgsjgjgjfj" -n vault-config-operator
```

```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: JWTOIDCAuthEngineConfig
metadata:
  name: azure-oidc
spec:
  authentication:
    path: kubernetes
    role: policy-vault-config-operator
    serviceAccount:
      name: controller-manager
  connection:
    address: 'https://vault.example.com:8200'
  defaultRole: personal-user
  OIDCClientID: ""
  OIDCCredentials:
    secret:
      name: oidccredentials
    usernameKey: oidc_client_id
    passwordKey: oidc_client_secret
  OIDCDiscoveryURL: "https://login.microsoftonline.com/<removed>/v2.0"
  path: oidc-aad
  providerConfig:
    {
      "provider": "azure"
    }
```

But I get the same error message.
