### ISSUE TITLE
`RandomSecret` is now appending a `data` folder as of v0.8.18

### ISSUE THREAD

**Issue by dlydiard** [redhat-cop/vault-config-operator#184]
Somewhere between v0.8.14 and v0.8.18 `RandomSecret` starting appending a `data` folder to the secret path.
Example:

```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: spatial-frontend-pipeline
  namespace: spatial-frontend-pipeline
spec:
  authentication:
    path: kubernetes/vault-config-application-configurator/aw-ue1-mt1
    role: pipeline
    serviceAccount:
      name: pipeline
  isKVSecretsEngineV2: true
  path: pipeline/kv/data/ci-automation/github-webhook-secrets/
  secretFormat:
    passwordPolicyName: 30-char-alphanumeric-only
  secretKey: secret
```

writes a secret value to `pipeline/kv/data/ci-automation/github-webhook-secrets/data/spatial-frontend-pipeline`
older versions of RandomSecret wrote the secret to `pipeline/kv/data/ci-automation/github-webhook-secrets/spatial-frontend-pipeline`

it seems like a `data` is being prepended to the `metadata.name` now. This is not desired since the final path does not match spec.path.

**Comment by davoustp** [comment]
I do confirm that I experience this problem as well.

All deployments upgrading to v0.8.18 is failing because of this issue - this makes it a blocker.

### Root cause analysis
This change comes from PR #175 merged and delivered in v0.8.17 (see https://github.com/redhat-cop/vault-config-operator/releases/tag/v0.8.17).

The idea of this PR is to remove the burden from the user to deal with the `/data` part of the path that Vault requires when dealing with kv-v2 by automatically adding it.

This is done by this code part: https://github.com/redhat-cop/vault-config-operator/blob/v0.8.17/api/v1alpha1/randomsecret_types.go#L95-L98

The logic added by this code change is to add the `/data` to the configured `path` attribute if not already there in the kv-v2 case.

_This logic is actually flawed_: the `/data` path segment must lie right after the kv-v2 mount path, but *before any path within this secret engine*, as specified in https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#create-update-secret :

> POST | /:secret-mount-path/data/:path

With vault-config-operator, the last segment of the path is the name of the `RandomSecret` entity.
But nothing prevents adding intermediate path levels between `/data` and this name - this is actually quite useful and normal with kv use cases.

Illustration with the `RandomSecret` below (few details stripped out for conciseness) using a kv-v2 engine mounted at `/kv/usage1`:
```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: myownsecret
spec:
  isKVSecretsEngineV2: true
  path: /kv/usage1/data/test
  secretKey: secret
```

This should create a kv-v2 secret at relative path `test/myownsecret` (full path: `/kv/usage1/data/test/myownsecret`, but this code change creates it at `test/data/myownsecret` (full path: `/kv/usage1/data/test/data/myownsecret`), which is wrong.

Note that specifying `path: /kv/usage1/test` (as this code change would have suggested) fails entirely, because the generated path is then `/kv/usage1/test/data/myownsecret` which is not API compliant and is rejected by the kv-v2 API endpoint.

### Potential mitigations

* Alternative 1

To allow the user to avoid dealing with the `/data` path segment her/himself, knowledge about the mount path of the kv-v2 secret engine is required: this would allow to insert this `/data` segment after the secret engine mount path if not already there.

This would require to query Vault for the kv-v2 secret mounts (hence also requiring the appropriate permissions to do so against `/sys/mounts` , see https://developer.hashicorp.com/vault/api-docs/system/mounts#list-mounted-secrets-engines ), get their mount paths, and strip the longest match against those mount paths from the `path` attribute to add the `/data` path segment if required.

It looks a pretty nasty heavy chunk to swallow...

* Alternative 2

Revert this logic change (and the corresponding doc section) - still leaving the doc improvements in place, though.

This peculiar `/data` path requirement in Vault's kv-v2 secret engine is disturbing for users, right, but it's Vault's own requirement - why should the vault-config-operator take care of doing this?

Attempting to hide this away from the user is also probably not a good idea, especially that this is clearly documented and advertised in Vault's documentation.

* Additional note

The RandomSecret admission controller (https://github.com/redhat-cop/vault-config-operator/blob/main/api/v1alpha1/kubernetessecretenginerole_webhook.go) could be slightly augmented to check that the `path` attribute does contain a `/data/` substring when attribute `isKVSecretsEngineV2` is `true`.

This would help users to understand immediately that there is a problem and avoid them scratching their head about why the secret is not created in Vault until they go checking the operator's log (which can be messy if there is activity going on).

@raffaelespazzoli and @trevorbox what's your take on this?
