### ISSUE TITLE
Helm chart certificate not valid for service name on mutating and validating webhook configurations 

### ISSUE THREAD

**Issue by thiago-juro** [redhat-cop/vault-config-operator#185]
Release v0.8.19, changed the service name in the mutating and validating webhook configuration. The certificate created with the chart doesn't cover the new name, so the config operator fails to reconcile with the following error:

`
1.6923463508608787e+09  ERROR   Reconciler error        {"controller": "authenginemount", "controllerGroup": "redhatcop.redhat.io", "controllerKind": "AuthEngineMount", "AuthEngineMount": {"name":"oidc","namespace":"vault"}, "namespace": "vault", "name": "oidc", "reconcileID": "caa4cb93-a4ae-4c7f-8a36-e05445371d98", "error": "Internal error occurred: failed calling webhook \"vauthenginemount.kb.io\": failed to call webhook: Post \"https://webhook-service.vault.svc:443/validate-redhatcop-redhat-io-v1alpha1-authenginemount?timeout=10s\": tls: failed to verify certificate: x509: certificate is valid for vault-config-operator-webhook-service.vault.svc, vault-config-operator-webhook-service.vault.svc.cluster.local, not webhook-service.vault.svc"}`

**Comment by davoustp** [comment]
The problem lies into the `MutatingWebhookConfiguration` object deployed by v0.8.19.

Differences below (some lines redacted / removed for reading ease).

With v0.8.18:
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-config-operator-mutating-webhook-configuration
webhooks:
- clientConfig:
    service:
      name: vault-config-operator-webhook-service
```

With v0.8.19:
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-config-operator-mutating-webhook-configuration
webhooks:
- clientConfig:
    service:
      name: webhook-service
```

Look at `webhooks.[].clientConfig.service.name`: it now erroneous uses `webhook-service` instead of `vault-config-operator-webhook-service` which obeviously does not match the SAN (DNS names) of the services declared into the TLS certificate, hence the error.
