### ISSUE TITLE
OLM update to 0.8.30 breaks kube-rbac-proxy

### ISSUE THREAD

**Issue by dabelenda** [redhat-cop/vault-config-operator#268]
OLM automatically updated the vault-config-operator to 0.8.30 yesterday, and since, the operator is broken with kube-rbac-proxy crashing due to absence of certificates:

```
I0320 07:19:25.693767       1 main.go:180] Valid token audiences: 
I0320 07:19:25.695071       1 main.go:316] Reading certificate files
F0320 07:19:25.695126       1 main.go:320] Failed to initialize certificate reloader: error loading certificates: error loading certificate: open /etc/certs/tls/tls.crt: no such file or directory
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00000e001, 0xc0002d6000, 0xc4, 0x1c6)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:996 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x22b1140, 0xc000000003, 0x0, 0x0, 0xc00057d500, 0x22097ed, 0x7, 0x140, 0x0)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:945 +0x191
k8s.io/klog/v2.(*loggingT).printf(0x22b1140, 0x3, 0x0, 0x0, 0x178f487, 0x2d, 0xc0001c7c38, 0x1, 0x1)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:733 +0x17a
k8s.io/klog/v2.Fatalf(...)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:1463
main.main()
	/home/runner/work/kube-rbac-proxy/kube-rbac-proxy/main.go:320 +0x20ee

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x22b1140)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:1131 +0x8b
created by k8s.io/klog/v2.init.0
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:416 +0xd8
```

In the Deployment, I can see, the arguments to use the certificate, the `volume` exists but it is not mounted correctly in `volumeMounts`.

```
      volumes:
      - name: tls-cert
        secret:
          defaultMode: 420
          secretName: vault-config-operator-certs
      - name: apiservice-cert
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: apiserver.crt
          - key: tls.key
            path: apiserver.key
          secretName: vault-config-operator-controller-manager-service-cert
      - name: webhook-cert
        secret:
          defaultMode: 420
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          secretName: vault-config-operator-controller-manager-service-cert
```

```
        volumeMounts:
        - mountPath: /apiserver.local.config/certificates
          name: apiservice-cert
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-cert
```

I tried to delete the deployment to see if OLM re-recreates it correctly, but it was exactly the same.

I only set environment variable `VAULT_ADDR` from the Subscription, so as a workaround I added the volumeMount in the subscription, too:

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/vault-config-operator.svc1215p-vault-config-operator: ""
    operators.coreos.com/vault-config-operator.vault-config-operator: ""
  name: vault-config-operator
  namespace: svc1215p-vault-config-operator
spec:
  channel: alpha
  config:
    env:
    - name: VAULT_ADDR
      value: REDACTED
    volumeMounts:
    - mountPath: /etc/certs/tls/
      name: tls-cert
```

**Comment by Nabsku** [comment]
Yep, running into the same issues on our end. There seem to be no changes to the deployment (in this repo in particular) but I cannot seem to find the actual operator manifest repository either..

**Comment by dabelenda** [comment]
What I can see in the Operators Repository is as follows.

In 0.8.29 there was a `volumeMounts` for the certificates of the kube-rbac-proxy:
https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/vault-config-operator/0.8.29/manifests/vault-config-operator.clusterserviceversion.yaml#L1918-L1920

In 0.8.30 there is no `volumeMounts` anymore:
https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/vault-config-operator/0.8.30/manifests/vault-config-operator.clusterserviceversion.yaml#L2163-L2195

However the `volumes` section is still present.

**Comment by raffaelespazzoli** [comment]
thank you for letting me know. We didn't change anything in the way the manifests are generated and the project is release. I will try to take a look as soon as possible. for now please use the workaround.

**Comment by dlydiard** [comment]
We hit the same issue - 0.8.29 worked, but after upgrading to 0.8.31, the proxy container crashed. Adding:

```yaml
volumeMounts:
- mountPath: /etc/certs/tls/
  name: tls-cert
```
to the Subscription fixed it.
