### ISSUE TITLE
singleton configurations should not have a finalizer as they cannot be deleted.

### ISSUE THREAD

**Issue by dlydiard** [redhat-cop/vault-config-operator#69]
When performing an ArgoCD rollback which attempted to delete the `KubernetesAuthEngineConfig` object, i received the following error:
```
- lastTransitionTime: '2022-08-10T15:11:50Z'
      message: "Error making API request.\n\nURL: DELETE https://vault.domain.dev:8200/v1/auth/kubernetes/vault-config-application-configurator/cluster-name/config\nCode: 405. Errors:\n\n* 1 error occurred:\n\t* unsupported operation\n\n"
      observedGeneration: 2
      reason: LastReconcileCycleFailed
      status: 'True'
      type: ReconcileError
```

example config:
```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    environment: production
  namespace: vault-authentication
  finalizers:
    - controller-kubernetesauthengineconfig
  labels:
    app.kubernetes.io/instance: cluster-configurations-cluster-name
spec:
  authentication:
    path: kubernetes/cluster-name
    role: vault-config-application-configurator
    serviceAccount:
      name: vault-config-operator
  disableISSValidation: false
  disableLocalCAJWT: false
  kubernetesCACert: |
     ....
    -----END CERTIFICATE-----
  kubernetesHost: 'https://api.cluster-name.p1.openshiftapps.com:6443/'
  path: kubernetes/vault-config-application-configurator
  tokenReviewerServiceAccount:
    name: vault-jwt-token-reviewer
```

I apologize, I was not able to get the Pod logs. I also cannot repeat this, it seems to happen intermittently for me.
